language: node_js
install: 
  - npm install
  - cd client && npm install
node_js: 
  - 'node'
before_script:
  - 'psql -c "CREATE DATABASE db_travis;" -U postgres'
  - 'psql -c "CREATE USER frohub WITH PASSWORD ''321396'';" -U postgres'
env:
  global:
    - PGPORT=5432
    - SECRET=frohub
services: 
  - mongodb
  - postgresql
test:
  adapter: postgresql
  database: db_travis
addons:
  postgresql: "10"
